apiVersion: apps/v1
kind: Deployment
metadata:
  name: mini-proje
spec:
  selector:
    matchLabels:
      app: mini-proje
  replicas: 1
  template:
    metadata:
      labels:
        app: mini-proje
    spec:
      containers:
        - name: mini-proje
          image: 'mini_proje:2.6'
          ports:
            - containerPort: 11130
          envFrom:
            -   configMapRef:
                    name: config-map